language: python

python:
  - 2.7

before_install:
  - sudo apt-get install -y libxml2-dev libxslt-dev

script: python setup.py test

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11

install:
  - export PYTHONPATH=$PWD;
  - export DJANGO_SETTINGS_MODULE=django_test_settings;
  - pip install -q Django==$DJANGO

branches:
  only:
    - master

after_success:
  - coveralls
